### ISSUE TITLE
User's settings POST gives Error 403

### ISSUE THREAD

**Issue by Brbb** [IntelligentTrading/telegram-bot#17]
## Description 

`/start` and `/settings` commands should save user's settings, but the response is:

CSRF verification failed. Request aborted.

You are seeing this message because this HTTPS site requires a `Referer header` to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.

**Comment by tomcounsell** [comment]
See updated readme docs
https://github.com/IntelligentTrading/data-sources/blob/tomcounsell-refactor-django/README.md

is_subscribed and is_muted should be sent as string, capitalized "True" or "False" or leave out to retain previous setting.

Referrer header no longer required. We will enforce referrer auth later

**Comment by tomcounsell** [comment]
200 response means all is set correctly
400 response means the POST was not structured or formatted correctly (didn't include a chat_id)
500 means there was a server-side error - a bug in the API endpoint and debug details might be sent in json response
