### ISSUE TITLE
Update production Bot commands list

### ISSUE THREAD

**Issue by Brbb** [IntelligentTrading/telegram-bot#21]
### Description

Update IntelligentTradingBot command list through https://telegram.me/BotFather

Paste the following list as commands list:

start - start ITT bot, subscribe to new alerts
help - list of available commands
settings - manager your preferences and profiles
feedback - send in any kind of  ideas or thoughts you may have on the ITT Trading Bot
price - the current valuation of a coin. For example: /price BTC
volume - last 24 hour volume data. For example: /volume BTC

**Comment by tomcounsell** [comment]
just updated for both IntelligentTradingBot and IntelligentTradingTestBot
