### ISSUE TITLE
Migrate the bot to Node on Heroku

### ISSUE THREAD

**Issue by Brbb** [IntelligentTrading/telegram-bot#9]
## Description
Refactor the current code in order to use node and run on Heroku 

### Solution
- [x] Set up the heroku environment
- [x] Port the code to the node-telegram-bot-api wrapper
- [ ] ~~Set a KEEPALIVE or PING system~~  
- [ ] Test and adjust the number of workers and the load balancing (over 70K users)

**Comment by tomcounsell** [comment]
with polling running well on heroku, I don't think we need a keepalive. 

We can put a health-check item in the backlog of things to build that will routinely test the chat and commands to make sure everything is working as expected, but it's not urgent.

Also for num of workers and balancing, we have a good architecture of microservices, so we shouldn't need to scale to multiple workers until we hit over 70,000 users (that's my rough estimation on current capacity)
